[package]
name = "vesper"
version = "0.1.6"
description = "Personal Assistant named Vesper lived in this desktop application"
authors = ["you"]
edition.workspace = true
rust-version.workspace = true
default-run = "vesper-desktop"

[[bin]]
name = "vesper-desktop"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "vesper_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
diesel.workspace = true
vesper-database.workspace = true
cms-core.workspace = true
consumers.workspace = true
games.workspace = true
futures-util.workspace = true
my-workspace-logger.workspace = true
music.workspace = true
ledger.workspace = true
percent-encoding.workspace = true
portable-pty.workspace = true
uuid.workspace = true
reqwest = { workspace = true, features = ["system-proxy"] }
quotes.workspace = true
serde.workspace = true
serde_json.workspace = true
social.workspace = true
sysinfo.workspace = true
tauri = { version = "2", features = ["devtools", "webview-data-url", "macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-updater = "2"
tempfile.workspace = true
tokio.workspace = true
todo-core.workspace = true
tracing.workspace = true
ugos.workspace = true
useage.workspace = true
vesper-credentials.workspace = true
tauri-plugin-notification = "2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-app-kit.workspace = true
objc2-foundation.workspace = true
