pub(super) const CSS: &str = r#"<style data-md-dialect="embeds">
.content-embed{color-scheme:light dark;box-sizing:border-box;margin:1.5rem auto;padding:1rem;overflow:hidden;border:1px solid light-dark(#d0cec6,#404040);border-radius:8px;background:light-dark(#f0efeb,#242424);box-shadow:0 4px 24px rgb(0 0 0/.05);color:light-dark(#24231f,#f0f0f0);font-family:var(--font-sans,ui-sans-serif,system-ui,sans-serif);text-decoration:none!important}
.content-embed-github,.content-embed-github *{text-decoration:none!important;border-bottom:0!important}.content-embed-github{display:grid;grid-template-columns:minmax(0,1fr) 3.5rem;align-items:center;gap:1rem;max-width:36rem}.content-embed-copy{display:grid;min-width:0;gap:.35rem}.content-embed-label{display:flex;align-items:center;gap:.35rem;color:light-dark(#787670,#a8a8a8);font-size:.68rem;font-weight:600;letter-spacing:.08em;text-transform:uppercase}.content-icon{width:.9rem;height:.9rem;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;vector-effect:non-scaling-stroke}.content-embed-meta>span,.content-stock-change{display:inline-flex;align-items:center;gap:.25rem}
.content-embed strong{overflow:hidden;color:light-dark(#141312,#f8f8f8);font-size:1.05rem;font-weight:500;text-overflow:ellipsis;white-space:nowrap}.content-embed-description{display:-webkit-box;overflow:hidden;color:light-dark(#5c5a55,#d0d0d0);font-size:.82rem;line-height:1.55;-webkit-box-orient:vertical;-webkit-line-clamp:2}.content-embed-meta{display:flex;flex-wrap:wrap;gap:.35rem .8rem;color:light-dark(#5c5a55,#d0d0d0);font-size:.72rem}.content-embed-avatar{width:3.5rem;height:3.5rem;border-radius:8px;object-fit:cover}
.content-embed-link,.content-embed-link *{text-decoration:none!important;border-bottom:0!important}.content-embed-link{display:flex;align-items:center;gap:1rem;max-width:36rem}.content-embed-link .content-embed-copy{flex:1}.content-embed-thumbnail{width:clamp(3.5rem,20%,7rem);height:5rem;flex-shrink:0;object-fit:cover;border-radius:6px}
.content-embed-stock{display:grid;grid-template-columns:minmax(9rem,.7fr) minmax(12rem,1.3fr);align-items:end;gap:1.5rem;min-height:10rem}.content-stock-quote{display:grid;align-content:start}.content-stock-name{overflow:hidden;margin:.15rem 0 .7rem;color:light-dark(#5c5a55,#d0d0d0);font-size:.78rem;text-overflow:ellipsis;white-space:nowrap}.content-stock-price{font-family:var(--font-mono,ui-monospace,monospace);font-size:1.65rem;line-height:1.15}.content-stock-change{margin-top:.3rem;font-family:var(--font-mono,ui-monospace,monospace);font-size:.75rem}.content-embed-up .content-stock-change,.content-embed-up .content-stock-visual{color:light-dark(#477c62,#72bc94)}.content-embed-down .content-stock-change,.content-embed-down .content-stock-visual{color:light-dark(#a64953,#da7d86)}.content-stock-chart{display:block;width:100%;height:6.5rem;overflow:visible}.content-stock-line{fill:none;stroke:currentColor;stroke-width:2.25;stroke-linecap:round;stroke-linejoin:round;vector-effect:non-scaling-stroke}.content-stock-area{stroke:none}.content-stock-end{fill:light-dark(#f0efeb,#242424);stroke:currentColor;stroke-width:2;vector-effect:non-scaling-stroke}.content-stock-range{display:flex;justify-content:space-between;margin-top:.25rem;color:light-dark(#787670,#a8a8a8);font-family:var(--font-mono,ui-monospace,monospace);font-size:.62rem}
.svg-canvas{margin:.75rem auto;padding:0;border:0;border-radius:0;background:transparent;box-shadow:none}.svg-canvas>svg{display:block;width:100%;height:auto;max-height:42rem}.svg-canvas-architecture{--canvas-ink:light-dark(#25241f,#e9e7df);--canvas-muted:light-dark(#6f6b62,#aaa69b);--canvas-line:light-dark(#aaa69b,#625f57);--canvas-purple:light-dark(#6f5a9a,#b7a4df);--canvas-teal:light-dark(#397b75,#72b8af);--canvas-coral:light-dark(#a95645,#e39787);--canvas-blue:light-dark(#476f9a,#86add8);--canvas-green:light-dark(#527a55,#8db590);--canvas-amber:light-dark(#976b2f,#dbad68);--canvas-red:light-dark(#a34949,#dc8989);background:transparent}.svg-canvas-architecture>svg{background:transparent;color:var(--canvas-ink);font-family:ui-sans-serif,system-ui,sans-serif}.svg-canvas-architecture .th{fill:var(--canvas-ink);font-size:14px;font-weight:650}.svg-canvas-architecture .t{fill:var(--canvas-ink);font-size:12px}.svg-canvas-architecture .ts{fill:var(--canvas-muted);font-size:10px}.svg-canvas-architecture .node rect,.svg-canvas-architecture .node path,.svg-canvas-architecture .box{fill:color-mix(in srgb,currentColor 9%,transparent);stroke:currentColor;stroke-width:1.25}.svg-canvas-architecture .arr,.svg-canvas-architecture .leader{fill:none;stroke:var(--canvas-line);stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round}.svg-canvas-architecture .leader{stroke-dasharray:4 5}.svg-canvas-architecture .c-purple{color:var(--canvas-purple)}.svg-canvas-architecture .c-teal{color:var(--canvas-teal)}.svg-canvas-architecture .c-coral{color:var(--canvas-coral)}.svg-canvas-architecture .c-blue{color:var(--canvas-blue)}.svg-canvas-architecture .c-green{color:var(--canvas-green)}.svg-canvas-architecture .c-amber{color:var(--canvas-amber)}.svg-canvas-architecture .c-red{color:var(--canvas-red)}.svg-canvas-architecture .c-gray{color:var(--canvas-line)}
.svg-canvas-storyboard{--board-ink:light-dark(#1b1b1f,#f1f3f5);--board-muted:light-dark(#868e96,#adb5bd);background:transparent}.svg-canvas-storyboard>svg{color:var(--board-ink);background:transparent;font-family:"Virgil","Comic Shanns","Comic Sans MS","Kaiti SC",cursive}.svg-canvas-storyboard .hand{fill:var(--board-ink);font-family:"Virgil","Comic Shanns","Comic Sans MS","Kaiti SC",cursive}.svg-canvas-storyboard .title{font-size:18px;font-weight:500}.svg-canvas-storyboard .caption{fill:var(--board-muted);font-size:12px}.svg-canvas-storyboard .step{fill:var(--board-stroke);font-size:11px}.svg-canvas-storyboard .note{fill:var(--board-fill);stroke:var(--board-stroke);stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.svg-canvas-storyboard .sketch,.svg-canvas-storyboard .arrow,.svg-canvas-storyboard .arrow-shadow,.svg-canvas-storyboard .scribble{fill:none;stroke:var(--board-stroke,var(--board-ink));stroke-linecap:round;stroke-linejoin:round}.svg-canvas-storyboard .sketch-shadow{fill:none;stroke:var(--board-stroke);stroke-width:1.05;stroke-linecap:round;stroke-linejoin:round;opacity:.55}.svg-canvas-storyboard .arrow{stroke-width:2}.svg-canvas-storyboard .arrow-shadow{stroke-width:.9;opacity:.55}.svg-canvas-storyboard .fill-blue{--board-fill:light-dark(#e7f5ff,#16324a);--board-stroke:light-dark(#1971c2,#74c0fc)}.svg-canvas-storyboard .fill-violet{--board-fill:light-dark(#f3f0ff,#2b2450);--board-stroke:light-dark(#6741d9,#b197fc)}.svg-canvas-storyboard .fill-green{--board-fill:light-dark(#ebfbee,#183c25);--board-stroke:light-dark(#2f9e44,#8ce99a)}.svg-canvas-storyboard .fill-orange{--board-fill:light-dark(#fff4e6,#492b16);--board-stroke:light-dark(#e8590c,#ffa94d)}.svg-canvas-storyboard .accent{--board-stroke:light-dark(#e03131,#ff8787)}.svg-canvas-storyboard .muted{--board-stroke:var(--board-muted)}
.content-embed-media{display:grid;gap:.65rem}.content-embed-media>audio,.content-embed-media>video{display:block;width:100%;max-width:100%;border-radius:var(--radius-sm,4px)}.content-embed-media>video{max-height:36rem}.content-embed-media>figcaption{margin:0;color:var(--color-muted-foreground,inherit);font-size:.82rem;line-height:1.5;overflow-wrap:anywhere}
.content-embed-article{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin:.5rem 0;padding:.75rem 1rem;border-color:var(--color-border,currentColor);border-radius:var(--radius-md,8px);background:var(--color-background,inherit);color:var(--color-foreground,inherit);box-shadow:none}.content-embed-article strong{white-space:normal;overflow-wrap:anywhere;color:inherit}.content-embed-article:focus-visible{outline:2px solid var(--color-accent,currentColor);outline-offset:2px}
.content-article-list{list-style:none!important;padding:0!important;margin:1rem 0;display:grid;gap:.5rem}.content-article-list>li{margin:0;min-width:0}.content-article-list .content-embed-article{margin:0}.content-article-list .content-embed-copy{min-width:0}.content-article-list .content-embed-description{white-space:normal;overflow-wrap:anywhere}
@media(max-width:40rem){.content-embed-stock{grid-template-columns:1fr;gap:1rem}.content-stock-chart{height:5.5rem}.content-embed{padding:.85rem}}
.content-article-list .content-embed.content-embed-article{padding:.5rem;justify-content:flex-start;border:0;background:transparent;border-radius:.5rem;color:var(--color-foreground,inherit)}
.content-embed-article:hover{background:var(--color-muted,transparent)}.content-embed-article .content-embed-copy{flex:1}.content-article-list .content-embed-article strong{font-size:1rem;font-weight:500;line-height:1.5}.content-embed-article .content-embed-description{color:var(--color-muted-foreground,inherit);font-size:.875rem;line-height:1.5}
.content-article-icon{display:block;position:relative;flex:0 0 2.75rem;height:3.5rem;border:1px solid var(--color-border,currentColor);border-radius:.375rem;background:var(--color-background,transparent)}.content-article-icon::before{content:"";position:absolute;inset:.75rem .5rem;background:repeating-linear-gradient(to bottom,var(--color-border,currentColor) 0 2px,transparent 2px 6px)}
.content-embed.content-embed-left,.content-article-list.content-embed-left{width:min(100%,32rem);margin-left:0;margin-right:auto}
.content-embed.content-embed-right,.content-article-list.content-embed-right{width:min(100%,32rem);margin-left:auto;margin-right:0}
.content-embed.content-embed-narrow,.content-article-list.content-embed-narrow{width:min(100%,32rem);margin-left:auto;margin-right:auto}
.content-embed-wide{width:100%}
.content-embed-quote blockquote{margin:0;padding:.25rem 0 .25rem 1rem;border-inline-start:3px solid var(--color-accent,currentColor)}
.content-embed-quote blockquote p{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}
.content-embed-quote figcaption,.content-embed-diff figcaption{margin:.75rem 0;color:var(--color-muted-foreground,inherit);font-size:.82rem;overflow-wrap:anywhere}
.content-embed-diff pre{margin:0;padding:.75rem 0;max-height:32rem;overflow:auto}
.content-embed-diff pre:focus-visible{outline:2px solid var(--color-accent,currentColor);outline-offset:2px}
.content-embed-diff code{display:block;min-width:max-content}
.content-embed-diff code span{display:block;padding:0 1rem;white-space:pre}
.content-embed-diff .diff-add{color:var(--color-success,inherit);background:color-mix(in srgb,var(--color-success,currentColor) 9%,transparent)}
.content-embed-diff .diff-remove{color:var(--color-error,inherit);background:color-mix(in srgb,var(--color-error,currentColor) 9%,transparent)}
.content-embed-diff .diff-header{color:var(--color-muted-foreground,inherit)}
.content-embed-annotation{--annotation-color:var(--color-chart-3,currentColor)}
.content-embed-annotation.annotation-red{--annotation-color:var(--color-error,currentColor)}
.content-embed-annotation.annotation-green{--annotation-color:var(--color-success,currentColor)}
.content-embed-annotation.annotation-amber{--annotation-color:var(--color-warning,currentColor)}
.content-embed-annotation.annotation-purple{--annotation-color:var(--color-chart-5,currentColor)}
.content-embed-annotation p{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}
.content-embed-annotation mark{color:inherit;background:color-mix(in srgb,var(--annotation-color) 18%,transparent);text-decoration:underline;text-decoration-color:var(--annotation-color);text-underline-offset:.2em}
.content-embed-annotation figcaption{margin-top:.75rem;padding-inline-start:.75rem;border-inline-start:2px solid var(--annotation-color);white-space:pre-wrap;overflow-wrap:anywhere;color:var(--color-muted-foreground,inherit)}
.architecture-flow.content-embed-left,.architecture-flow.content-embed-right,.architecture-flow.content-embed-narrow{width:min(100%,32rem)}.architecture-flow.content-embed-left{margin-left:0;margin-right:auto}.architecture-flow.content-embed-right{margin-left:auto;margin-right:0}.architecture-flow.content-embed-narrow{margin-left:auto;margin-right:auto}
.architecture-flow{container-type:inline-size;min-width:0;max-width:100%}.architecture-flow .svg-canvas>svg{max-height:none}.architecture-flow .architecture-compact{display:none}
@container(max-width:640px){.architecture-flow .architecture-wide{display:none}.architecture-flow .architecture-compact{display:block}}
</style>
"#;
