[package]
name = "ledger"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
diesel.workspace = true
vesper-database.workspace = true
serde.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
