[package]
name = "md-dialect"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
futures-util.workspace = true
pulldown-cmark.workspace = true
quotes.workspace = true
url.workspace = true
percent-encoding.workspace = true
svg-hush.workspace = true
thiserror.workspace = true
